name: Publish to TestPyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install build dependencies  # Make sure 'build' is installed!
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Verify installed packages (debugging)
        run: pip list

      - name: Build package
        run: python -m build  # This should work now

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
